### ISSUE TITLE
Get version from GitHub release

### ISSUE THREAD

**Issue by tenhobi** [ncipollo/semantic-version-action#2]
It would be helpful not only to get the version from tag reference, but also from the last github release tag.

**Comment by ncipollo** [comment]
Could you elaborate a bit more on your use case? Are you attempting to run the action prior to the tag existing (for example triggered from a create release event)?

**Comment by tenhobi** [comment]
@ncipollo yes, exactly. although more I think of it, it is functionality beyond this action.
